<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Test Setup add Test" tests="4" failures="1" timestamp="2 Nov 2017 09:11:37 GMT" time="157.35" errors="0">
  <testcase name="Login" time="1.164" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
  <testcase name="TargetPage" time="66.889" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
  <testcase name="Add_Questions" time="20.114" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
  <testcase name="Add_Questions" time="31.537" classname="Module.HRSetup.General.TC030_TestSetupAddTest">
    <failure type="java.lang.AssertionError" message="Record not Added Successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Record not Added Successfully expected [true] but found [false]
	at pom.ObjectPages.uiActions.TestSetup.Test_VerifyRecord(TestSetup.java:124)
	at Module.HRSetup.General.TC030_TestSetupAddTest.Add_Questions(TC030_TestSetupAddTest.java:84)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Add_Questions -->
</testsuite> <!-- Test Setup add Test -->
