<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval" tests="4" failures="0" timestamp="20 Nov 2017 07:29:00 GMT" time="81.717" errors="1">
  <testcase name="TargetPage" time="65.179" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval"/>
  <testcase name="LeaveApproveReject" time="14.190" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval"/>
  <testcase name="LeaveApproveReject" time="0.893" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval">
    <error type="org.testng.SkipException" message="28-Sep-17 checkbox is not found">
      <![CDATA[org.testng.SkipException: 28-Sep-17 checkbox is not found
	at pom.ObjectPages.uiActions.AttendanceApproval.Test_AttendanceApproveReject(AttendanceApproval.java:77)
	at Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval.LeaveApproveReject(TC011_AttendanceApproval.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- LeaveApproveReject -->
  <testcase name="Login" time="1.455" classname="Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval"/>
</testsuite> <!-- Module.ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval -->
