<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.HRSetup.General.TC030_TestSetupAddTest" tests="4" failures="1" timestamp="21 Nov 2017 13:16:06 GMT" time="91.255" errors="0">
  <testcase name="Add_Test" time="24.522" classname="Module.HRSetup.General.TC030_TestSetupAddTest">
    <failure type="java.lang.AssertionError" message="Expected : [Add New Button] But Found : [Welcome to Onex Software]">
      <![CDATA[java.lang.AssertionError: Expected : [Add New Button] But Found : [Welcome to Onex Software]
	at org.testng.Assert.fail(Assert.java:94)
	at pom.ObjectPages.uiActions.TestSetup.Test_AddNewRecord(TestSetup.java:115)
	at Module.HRSetup.General.TC030_TestSetupAddTest.Add_Test(TC030_TestSetupAddTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- Add_Test -->
  <testcase name="Login" time="1.217" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
  <testcase name="Add_Test" time="23.343" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
  <testcase name="TargetPage" time="42.173" classname="Module.HRSetup.General.TC030_TestSetupAddTest"/>
</testsuite> <!-- Module.HRSetup.General.TC030_TestSetupAddTest -->
