<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval" tests="3" failures="0" timestamp="6 Oct 2017 07:37:18 GMT" time="0.005" errors="3">
  <testcase name="Login" time="0.005" classname="ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.TestBase.TestBase.closeBrowser(TestBase.java:369)
	at pom.TestBase.TestBase.endTest(TestBase.java:363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Login -->
  <testcase name="TargetPage" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval">
    <error type="java.lang.Throwable" message="Method TC011_AttendanceApproval.TargetPage()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval@514af7] depends on not successfully finished methods in group &quot;aalogin&quot;">
      <![CDATA[java.lang.Throwable: Method TC011_AttendanceApproval.TargetPage()[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval@514af7] depends on not successfully finished methods in group "aalogin"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- TargetPage -->
  <testcase name="LeaveApproveReject" time="0.000" classname="ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval">
    <error type="java.lang.Throwable" message="Method TC011_AttendanceApproval.LeaveApproveReject(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval@514af7] depends on not successfully finished methods in group &quot;aatargetpage&quot;">
      <![CDATA[java.lang.Throwable: Method TC011_AttendanceApproval.LeaveApproveReject(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval@514af7] depends on not successfully finished methods in group "aatargetpage"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1040)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- LeaveApproveReject -->
</testsuite> <!-- ESS.LeaveandAttendance.LeaveApplication.TC011_AttendanceApproval -->
